version: "3.9"

networks:
  default:
    name: find-me-net

services:
  find-me-alert:
    container_name: find-me-alert
    restart: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - default
    command: yarn serve
    env_file:
      - .env
    ports:
      - "3001:3001"
